AWSTemplateFormatVersion: "2010-09-09"

Mappings:
  RegionMap:
    ap-southeast-1:
      "AMI": "ami-08569b978cc4dfa10"
    ap-northeast-1:
      "AMI": "ami-06cd52961ce9f0d85"
    us-east-1:
      "AMI": "ami-048f6ed62451373d9"

Resources:

  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      Tags:
        - Key: Name
          Value: Mapping Demo Server

Outputs:
  URL:
    Description: URL of the sample website
    Value: !Sub 'http://${EC2Instance.PublicDnsName}'